package com.red.dxbc.chunks.shdr.enums;

import com.shade.platform.model.util.EnumValue;

public enum D3D10Opcode implements EnumValue {
    ADD,
    AND,
    BREAK,
    BREAKC,
    CALL,
    CALLC,
    CASE,
    CONTINUE,
    CONTINUEC,
    CUT,
    DEFAULT,
    DERIV_RTX,
    DERIV_RTY,
    DISCARD,
    DIV,
    DP2,
    DP3,
    DP4,
    ELSE,
    EMIT,
    EMITTHENCUT,
    ENDIF,
    ENDLOOP,
    ENDSWITCH,
    EQ,
    EXP,
    FRC,
    FTOI,
    FTOU,
    GE,
    IADD,
    IF,
    IEQ,
    IGE,
    ILT,
    IMAD,
    IMAX,
    IMIN,
    IMUL,
    INE,
    INEG,
    ISHL,
    ISHR,
    ITOF,
    LABEL,
    LD,
    LD_MS,
    LOG,
    LOOP,
    LT,
    MAD,
    MIN,
    MAX,
    CUSTOMDATA,
    MOV,
    MOVC,
    MUL,
    NE,
    NOP,
    NOT,
    OR,
    RESINFO,
    RET,
    RETC,
    ROUND_NE,
    ROUND_NI,
    ROUND_PI,
    ROUND_Z,
    RSQ,
    SAMPLE,
    SAMPLE_C,
    SAMPLE_C_LZ,
    SAMPLE_L,
    SAMPLE_D,
    SAMPLE_B,
    SQRT,
    SWITCH,
    SINCOS,
    UDIV,
    ULT,
    UGE,
    UMUL,
    UMAD,
    UMAX,
    UMIN,
    USHR,
    UTOF,
    XOR,
    DCL_RESOURCE, // DCL* opcodes have
    DCL_CONSTANT_BUFFER, // custom operand formats.
    DCL_SAMPLER,
    DCL_INDEX_RANGE,
    DCL_GS_OUTPUT_PRIMITIVE_TOPOLOGY,
    DCL_GS_INPUT_PRIMITIVE,
    DCL_MAX_OUTPUT_VERTEX_COUNT,
    DCL_INPUT,
    DCL_INPUT_SGV,
    DCL_INPUT_SIV,
    DCL_INPUT_PS,
    DCL_INPUT_PS_SGV,
    DCL_INPUT_PS_SIV,
    DCL_OUTPUT,
    DCL_OUTPUT_SGV,
    DCL_OUTPUT_SIV,
    DCL_TEMPS,
    DCL_INDEXABLE_TEMP,
    DCL_GLOBAL_FLAGS,

// -----------------------------------------------

    RESERVED0,

// ---------- DX 10.1 op codes---------------------

    LOD,
    GATHER4,
    SAMPLE_POS,
    SAMPLE_INFO,
    D3D10_1_SB_OPCODE_RESERVED1,

    // ---------- DX 11 op codes---------------------
    HS_DECLS, // token marks beginning of HS sub-shader
    HS_CONTROL_POINT_PHASE, // token marks beginning of HS sub-shader
    HS_FORK_PHASE, // token marks beginning of HS sub-shader
    HS_JOIN_PHASE, // token marks beginning of HS sub-shader

    EMIT_STREAM,
    CUT_STREAM,
    EMITTHENCUT_STREAM,
    INTERFACE_CALL,

    BUFINFO,
    DERIV_RTX_COARSE,
    DERIV_RTX_FINE,
    DERIV_RTY_COARSE,
    DERIV_RTY_FINE,
    GATHER4_C,
    GATHER4_PO,
    GATHER4_PO_C,
    RCP,
    F32TOF16,
    F16TOF32,
    UADDC,
    USUBB,
    COUNTBITS,
    FIRSTBIT_HI,
    FIRSTBIT_LO,
    FIRSTBIT_SHI,
    UBFE,
    IBFE,
    BFI,
    BFREV,
    SWAPC,

    DCL_STREAM,
    DCL_FUNCTION_BODY,
    DCL_FUNCTION_TABLE,
    DCL_INTERFACE,

    DCL_INPUT_CONTROL_POINT_COUNT,
    DCL_OUTPUT_CONTROL_POINT_COUNT,
    DCL_TESS_DOMAIN,
    DCL_TESS_PARTITIONING,
    DCL_TESS_OUTPUT_PRIMITIVE,
    DCL_HS_MAX_TESSFACTOR,
    DCL_HS_FORK_PHASE_INSTANCE_COUNT,
    DCL_HS_JOIN_PHASE_INSTANCE_COUNT,

    DCL_THREAD_GROUP,
    DCL_UNORDERED_ACCESS_VIEW_TYPED,
    DCL_UNORDERED_ACCESS_VIEW_RAW,
    DCL_UNORDERED_ACCESS_VIEW_STRUCTURED,
    DCL_THREAD_GROUP_SHARED_MEMORY_RAW,
    DCL_THREAD_GROUP_SHARED_MEMORY_STRUCTURED,
    DCL_RESOURCE_RAW,
    DCL_RESOURCE_STRUCTURED,
    LD_UAV_TYPED,
    STORE_UAV_TYPED,
    LD_RAW,
    STORE_RAW,
    LD_STRUCTURED,
    STORE_STRUCTURED,
    ATOMIC_AND,
    ATOMIC_OR,
    ATOMIC_XOR,
    ATOMIC_CMP_STORE,
    ATOMIC_IADD,
    ATOMIC_IMAX,
    ATOMIC_IMIN,
    ATOMIC_UMAX,
    ATOMIC_UMIN,
    IMM_ATOMIC_ALLOC,
    IMM_ATOMIC_CONSUME,
    IMM_ATOMIC_IADD,
    IMM_ATOMIC_AND,
    IMM_ATOMIC_OR,
    IMM_ATOMIC_XOR,
    IMM_ATOMIC_EXCH,
    IMM_ATOMIC_CMP_EXCH,
    IMM_ATOMIC_IMAX,
    IMM_ATOMIC_IMIN,
    IMM_ATOMIC_UMAX,
    IMM_ATOMIC_UMIN,
    SYNC,

    DADD,
    DMAX,
    DMIN,
    DMUL,
    DEQ,
    DGE,
    DLT,
    DNE,
    DMOV,
    DMOVC,
    DTOF,
    FTOD,

    EVAL_SNAPPED,
    EVAL_SAMPLE_INDEX,
    EVAL_CENTROID,

    DCL_GS_INSTANCE_COUNT,

    ABORT,
    DEBUG_BREAK,

// -----------------------------------------------

    // This marks the end of D3D11.0 opcodes
    RESERVED1,

    DDIV,
    DFMA,
    DRCP,

    MSAD,

    DTOI,
    DTOU,
    ITOD,
    UTOD,

// -----------------------------------------------

    // This marks the end of D3D11.1 opcodes
    RESERVED2,

    GATHER4_FEEDBACK,
    GATHER4_C_FEEDBACK,
    GATHER4_PO_FEEDBACK,
    GATHER4_PO_C_FEEDBACK,
    LD_FEEDBACK,
    LD_MS_FEEDBACK,
    LD_UAV_TYPED_FEEDBACK,
    LD_RAW_FEEDBACK,
    LD_STRUCTURED_FEEDBACK,
    SAMPLE_L_FEEDBACK,
    SAMPLE_C_LZ_FEEDBACK,

    SAMPLE_CLAMP_FEEDBACK,
    SAMPLE_B_CLAMP_FEEDBACK,
    SAMPLE_D_CLAMP_FEEDBACK,
    SAMPLE_C_CLAMP_FEEDBACK,

    CHECK_ACCESS_FULLY_MAPPED,

// -----------------------------------------------

    // This marks the end of WDDM 1.3 opcodes
    RESERVED4,
    NUM_OPCODES;                                     // Should be the last entry

    @Override
    public int value() {
        return ordinal();
    }
}
