package com.red.dxbc.chunks.xsgn;

import com.shade.platform.model.util.EnumValue;

public enum D3DName implements EnumValue {
    UNDEFINED(0),
    POSITION(1),
    CLIP_DISTANCE(2),
    CULL_DISTANCE(3),
    RENDER_TARGET_ARRAY_INDEX(4),
    VIEWPORT_ARRAY_INDEX(5),
    VERTEX_ID(6),
    PRIMITIVE_ID(7),
    INSTANCE_ID(8),
    IS_FRONT_FACE(9),
    SAMPLE_INDEX(10),
    FINAL_QUAD_EDGE_TESSFACTOR(11),
    FINAL_QUAD_INSIDE_TESSFACTOR(12),
    FINAL_TRI_EDGE_TESSFACTOR(13),
    FINAL_TRI_INSIDE_TESSFACTOR(14),
    FINAL_LINE_DETAIL_TESSFACTOR(15),
    FINAL_LINE_DENSITY_TESSFACTOR(16),
    BARYCENTRICS(23),
    SHADINGRATE(24),
    CULLPRIMITIVE(25),
    TARGET(64),
    DEPTH(65),
    COVERAGE(66),
    DEPTH_GREATER_EQUAL(67),
    DEPTH_LESS_EQUAL(68),
    STENCIL_REF(69),
    INNER_COVERAGE(70),
    D3D10_UNDEFINED(71),
    D3D10_POSITION(72),
    D3D10_CLIP_DISTANCE(73),
    D3D10_CULL_DISTANCE(74),
    D3D10_RENDER_TARGET_ARRAY_INDEX(75),
    D3D10_VIEWPORT_ARRAY_INDEX(76),
    D3D10_VERTEX_ID(77),
    D3D10_PRIMITIVE_ID(78),
    D3D10_INSTANCE_ID(79),
    D3D10_IS_FRONT_FACE(80),
    D3D10_SAMPLE_INDEX(81),
    D3D10_TARGET(82),
    D3D10_DEPTH(83),
    D3D10_COVERAGE(84),
    D3D11_FINAL_QUAD_EDGE_TESSFACTOR(85),
    D3D11_FINAL_QUAD_INSIDE_TESSFACTOR(86),
    D3D11_FINAL_TRI_EDGE_TESSFACTOR(87),
    D3D11_FINAL_TRI_INSIDE_TESSFACTOR(88),
    D3D11_FINAL_LINE_DETAIL_TESSFACTOR(89),
    D3D11_FINAL_LINE_DENSITY_TESSFACTOR(90),
    D3D11_DEPTH_GREATER_EQUAL(91),
    D3D11_DEPTH_LESS_EQUAL(92),
    D3D11_STENCIL_REF(93),
    D3D11_INNER_COVERAGE(94),
    D3D12_BARYCENTRICS(95),
    D3D12_SHADINGRATE(96),
    D3D12_CULLPRIMITIVE(97);

    private final int value;

    D3DName(int value) {
        this.value = value;
    }

    @Override
    public int value() {
        return value;
    }
}
